travis:
  secure:
    BINSTAR_TOKEN: hwYs0P3+maZ8J91iB66TjTeZ6XfJQnR9w3Uyb7WnDap6CdzthtP2Bzop++GgrdklWIx4uCFqtF3V6G6IZE2bBSGOAbl4CJ3ZduqN3SNL9atHjsV6EJh4AIV5dveQ8CU4eUmfnpZIJF8iWtAa/pGGcM2JuKVuNIR4N3Nkynf5D/bwCmL2SyxpD3kKl4bExGhB+8CWkoTTHlYj6tfeiGjIlPz0gv0AdVfrn0WmI/9rBK8fw4o0tMrAxdrjR1MeB0mPAFkSYyYiGPhgcEQCNv0sM+FOVr7bgLMnhG20ea+JXO3EhHgBKDRABbEwMuLc6F0k04qMVR93vzDmZGAC/AaRVhVkTmVovvqpUYpG8qrK8baBdPRKUrvjPo2P5SP2twOHBJW+Z2z1EgC/aeK1G4WRqHDe4bPJQhhyz5UdhiXLo6hCtKnsEXdIdSNxNNax/k178KJ3wGDC6vwptjvq9NjsxKBjodPa/6zJCl39kf9LZK1Ke0/206JJGYERxB/d5AT8h/xrPzeZML6xKlndxI0vzcsJamxMb+WQvowfrpDFEPYCB1tXaKUTMKyqfmOP/pq61dh7TyITO5T1OJqUvM6FVfLrdeD+06LRwZ01DQ5p1eTnb+8ThK9KmvMiBXSfdYRvx74ivTW4igTXBCbEp1072TQYfTHYpG2d1oQAdzjFe9o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
