travis:
  secure:
    BINSTAR_TOKEN: cP2I9T0PuZWZEAMONqKNsy9oDYhait3xw1Je8VX2s+IGodsDH9llYx4OPbgZmUmiY3PmnHZIYUaNT4EVuv9/1CIcLL8/2yYsES+fH1haOElyzwhhaZ7FqhEtcncnrdBSBklXYH7DLH3jcvAnXzYZf15UEPrlbY56xsU23ulyl1EWQZx+UODGnvYMBlQ3AAWKFsO4fZlrNxfU0wxxHbKxnMfl9KzKh4gWZPE+xUyTL/YS1HiKneTbi4FzP3RDbEE/4qMJq+L2rDUU0sj7NskhkwZd4X5V5RPrWXhVIU+GhjY9Bp3OIoXyjFcHM4JdsloncTONKWWOTW6xeHv4vPugbOLcGf+UMJlg2x3WWTLfuPGVDtatWAJpXiFXfY2B2gu1HPypEU8QxO5mvehgBLXvXFnyLh76EADcxK8Y98hTFMf0U0J68xqAfSu4MGhXdfMkny8po4yOF+myo7mIaYgx9i/BZSNe71SyQokZd3siPblrabF8FRyUwzgyuW3zCkfH08cybjadxaJAijY7XaF50o8bFZ2Pgl5rhGxjwKtN4vUvF3PUZltD2/PXEtBR6LeWL/ggSP6TwV5uUdlLoEvNgfC8xbkhZYZ4ylRefASwkHIqGpraKuv5tyQh0p45+GzsgEtFegVew2utQm6ozVapQpcmglGSwKdU/tMOhQhKykE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
